In [1]:
import numpy as np
x2 = np.random.randint(10, size=(3, 4)) 

In [8]:
x2

array([[99,  1,  6,  7],
       [ 1,  9,  1,  6],
       [ 6,  5,  2,  5]])

In [3]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[1 1]
 [1 9]]


In [4]:
x2_sub[0,0]=99
print(x2_sub)

[[99  1]
 [ 1  9]]


In [6]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  1]
 [ 1  9]]


In [7]:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

[[42  1]
 [ 1  9]]


In [9]:
x2

array([[99,  1,  6,  7],
       [ 1,  9,  1,  6],
       [ 6,  5,  2,  5]])

In [10]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
x=np.array([1,2,3])
x.reshape((1,3))

array([[1, 2, 3]])

In [13]:
x.reshape((2,3))

ValueError: cannot reshape array of size 3 into shape (2,3)

In [14]:
x[np.newaxis, :]

array([[1, 2, 3]])

In [15]:
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [16]:
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [17]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [18]:
z = [199, 198, 197]
print(np.concatenate([x, y, z]))

[  1   2   3   3   2   1 199 198 197]


In [19]:
grid = np.array([[1, 2, 3],
                [4, 5, 6]])

In [20]:
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [21]:
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [22]:
np.concatenate([grid, grid], axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [23]:
grid = np.array([[41, 42, 43],
                 [54, 55, 56]])

In [24]:
np.concatenate([grid, grid], axis=0)

array([[41, 42, 43],
       [54, 55, 56],
       [41, 42, 43],
       [54, 55, 56]])

In [25]:
np.concatenate([grid, grid], axis=1)

array([[41, 42, 43, 41, 42, 43],
       [54, 55, 56, 54, 55, 56]])

In [34]:
x = np.array([[1],
              [2]])
grid = np.array([[9, 8],
                 [6, 5]])
# vertically stack the arrays
np.hstack([grid, x])

array([[9, 8, 1],
       [6, 5, 2]])

In [36]:
import numpy as np
np.random.seed(0)

def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
         output[i] = 1.0 / values[i]
    return output

values = np.random.randint(1, 10, size=5)
compute_reciprocals(values)

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [37]:
values = np.random.randint(1, 10, size=5)
compute_reciprocals(values)

array([0.25      , 0.16666667, 0.33333333, 0.2       , 0.125     ])

In [38]:
values = np.random.randint(1, 10, size=5)
compute_reciprocals(values)

array([0.14285714, 0.11111111, 0.11111111, 0.5       , 0.14285714])

In [40]:
big_array = np.random.randint(1, 100, size=1000000)
%timeit compute_reciprocals(big_array)

1 loop, best of 3: 258 ms per loop


In [41]:
compute_reciprocals(big_array)

array([0.01315789, 0.01075269, 0.0106383 , ..., 0.02631579, 0.01351351,
       0.02857143])

In [43]:
big_array = np.random.randint(1, 100, size=1000000)
compute_reciprocals(big_array)

array([0.015625  , 0.01149425, 0.03448276, ..., 0.01315789, 0.01818182,
       0.02702703])

In [44]:
print(compute_reciprocals(values))
print(1.0 / values)

[0.14285714 0.11111111 0.11111111 0.5        0.14285714]
[0.14285714 0.11111111 0.11111111 0.5        0.14285714]


In [45]:
%timeit (1.0 / big_array)

100 loops, best of 3: 3.17 ms per loop


In [46]:
%timeit (1.0 / big_array)

100 loops, best of 3: 3.15 ms per loop


In [47]:
np.arange(5) / np.arange(1, 6)

array([0, 0, 0, 0, 0])

In [48]:
np.arange(5) / np.arange(1, 6)

array([0, 0, 0, 0, 0])

In [49]:
x = np.arange(9).reshape((3, 3))
2 ** x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]])

In [50]:
x = np.arange(4)
print("x =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2) 

('x =', array([0, 1, 2, 3]))
('x + 5 =', array([5, 6, 7, 8]))
('x - 5 =', array([-5, -4, -3, -2]))
('x * 2 =', array([0, 2, 4, 6]))
('x / 2 =', array([0, 0, 1, 1]))
('x // 2 =', array([0, 0, 1, 1]))


In [51]:
-(0.5*x + 1) ** 2

array([-1.  , -2.25, -4.  , -6.25])

In [52]:
np.add(x, 2)

array([2, 3, 4, 5])